name: Build and Deploy Docs

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          cd docs
          pip install -r requirements.txt  # Adjust based on your project

      - name: Build HTML
        run: |
          cd docs
          sphinx-build -b html . _build # Adjust this command based on your Sphinx setup
          ls

      - name: Deploy to GitHub Pages
        run: |
          cd docs
          cp _build ../ -r
          cd ..
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add _build
          git commit -m "Deploy Sphinx documentation"
          git push
